import { useState } from 'react';
import { Loader2, Play, Pause, Download, Share2, ArrowLeft, Image as ImageIcon } from 'lucide-react';

const DURATIONS = [
  { label: '30 Seconds', value: 30 },
  { label: '1 Minute', value: 60 },
  { label: '10 Minutes', value: 600 },
  { label: '1 Hour', value: 3600 },
];

export default function ImageToVideo({ onBack }) {
  const [file, setFile] = useState(null);
  const [preview, setPreview] = useState('');
  const [duration, setDuration] = useState(60);
  const [loading, setLoading] = useState(false);
  const [videoUrl, setVideoUrl] = useState('');
  const [error, setError] = useState('');

  const onFileChange = (e) => {
    const f = e.target.files?.[0];
    if (!f) return;
    setFile(f);
    setPreview(URL.createObjectURL(f));
  };

  const handleGenerate = async () => {
    setError('');
    if (!file) {
      setError('Please upload an image.');
      return;
    }
    if (duration > 60) {
      setError('For demo, please choose up to 1 minute.');
      return;
    }

    setLoading(true);
    setVideoUrl('');
    try {
      const formData = new FormData();
      formData.append('image', file);
      formData.append('duration_seconds', String(duration));

      const res = await fetch(`${import.meta.env.VITE_BACKEND_URL || ''}/api/generate-image-video`, {
        method: 'POST',
        body: formData,
      });
      const data = await res.json();
      if (!res.ok) throw new Error(data?.detail || 'Failed to generate');
      setVideoUrl(data.url);
    } catch (e) {
      setError(e.message || 'Something went wrong');
    } finally {
      setLoading(false);
    }
  };

  return (
    <section className="flex-1 w-full max-w-5xl mx-auto px-6 pt-10 pb-20">
      <button onClick={onBack} className="mb-6 inline-flex items-center gap-2 text-slate-300 hover:text-white">
        <ArrowLeft className="w-4 h-4" /> Back
      </button>

      <div className="relative rounded-2xl bg-slate-900/60 ring-1 ring-white/10 p-6 backdrop-blur-sm">
        <h2 className="text-2xl font-bold mb-4">Image to Video</h2>

        <label className="block">
          <div className="w-full rounded-lg border border-dashed border-white/15 bg-slate-800/50 p-6 text-center cursor-pointer hover:bg-slate-800/70 transition">
            <input type="file" accept="image/*" onChange={onFileChange} className="hidden" />
            <div className="flex flex-col items-center gap-2 text-slate-300">
              <ImageIcon className="w-6 h-6" />
              <span>Drag & drop or click to upload image</span>
            </div>
          </div>
        </label>

        {preview && (
          <div className="mt-4">
            <img src={preview} alt="preview" className="w-full max-h-80 object-contain rounded-lg" />
          </div>
        )}

        <div className="mt-4 flex flex-col sm:flex-row gap-4 items-center">
          <select
            className="w-full sm:w-auto bg-slate-800/70 ring-1 ring-white/10 rounded-lg px-4 py-2"
            value={duration}
            onChange={(e) => setDuration(Number(e.target.value))}
          >
            {DURATIONS.map((d) => (
              <option key={d.value} value={d.value}>{d.label}</option>
            ))}
          </select>
          <button
            onClick={handleGenerate}
            disabled={loading}
            className="inline-flex items-center justify-center gap-2 rounded-xl bg-gradient-to-r from-indigo-500 via-sky-500 to-purple-500 px-6 py-3 text-base font-semibold text-white shadow-lg shadow-indigo-900/30 disabled:opacity-60"
          >
            {loading ? <Loader2 className="w-5 h-5 animate-spin" /> : null}
            {loading ? 'Generating...' : 'Generate Video'}
          </button>
        </div>
        {loading && (
          <div className="mt-6 h-2 w-full bg-slate-800 rounded-full overflow-hidden">
            <div className="h-full w-1/3 animate-[progress_1.2s_ease_infinite] bg-gradient-to-r from-indigo-500 via-sky-500 to-purple-500" />
          </div>
        )}
        {error && <p className="mt-4 text-red-400 text-sm">{error}</p>}
      </div>

      {videoUrl && (
        <div className="mt-8 rounded-2xl bg-slate-900/60 ring-1 ring-white/10 p-6">
          <div className="relative">
            <video id="preview-video" className="w-full rounded-lg" src={videoUrl} controls />
            <span className="absolute bottom-2 right-2 text-[10px] text-white/80 bg-black/50 px-2 py-1 rounded">Generated by VisionFlow AI</span>
          </div>
          <div className="mt-4 flex flex-wrap gap-3">
            <a href={videoUrl} download className="inline-flex items-center gap-2 px-4 py-2 rounded-lg bg-slate-800/80">
              <Download className="w-4 h-4" /> Download
            </a>
            <button onClick={() => navigator.share ? navigator.share({ title: 'VisionFlow AI Video', url: videoUrl }) : navigator.clipboard.writeText(videoUrl)} className="inline-flex items-center gap-2 px-4 py-2 rounded-lg bg-slate-800/80">
              <Share2 className="w-4 h-4" /> Share
            </button>
          </div>
        </div>
      )}

      <style>{`
        @keyframes progress { 0%{transform:translateX(-100%)} 50%{transform:translateX(0%)} 100%{transform:translateX(100%)} }
      `}</style>
    </section>
  );
}
