import { useState } from 'react';
import { Loader2, Play, Pause, Download, Share2, ArrowLeft } from 'lucide-react';

const DURATIONS = [
  { label: '30 Seconds', value: 30 },
  { label: '1 Minute', value: 60 },
  { label: '10 Minutes', value: 600 },
  { label: '1 Hour', value: 3600 },
];

export default function TextToVideo({ onBack }) {
  const [prompt, setPrompt] = useState('');
  const [duration, setDuration] = useState(60);
  const [loading, setLoading] = useState(false);
  const [videoUrl, setVideoUrl] = useState('');
  const [playing, setPlaying] = useState(false);
  const [error, setError] = useState('');

  const handleGenerate = async () => {
    setError('');
    if (!prompt.trim()) {
      setError('Please enter a description.');
      return;
    }
    // Limit free generation to <= 60s in UI
    if (duration > 60) {
      setError('For demo, please choose up to 1 minute.');
      return;
    }

    setLoading(true);
    setVideoUrl('');
    try {
      const res = await fetch(`${import.meta.env.VITE_BACKEND_URL || ''}/api/generate-text-video`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ prompt, duration_seconds: duration }),
      });
      const data = await res.json();
      if (!res.ok) throw new Error(data?.detail || 'Failed to generate');
      setVideoUrl(data.url);
    } catch (e) {
      setError(e.message || 'Something went wrong');
    } finally {
      setLoading(false);
    }
  };

  return (
    <section className="flex-1 w-full max-w-5xl mx-auto px-6 pt-10 pb-20">
      <button onClick={onBack} className="mb-6 inline-flex items-center gap-2 text-slate-300 hover:text-white">
        <ArrowLeft className="w-4 h-4" /> Back
      </button>

      <div className="relative rounded-2xl bg-slate-900/60 ring-1 ring-white/10 p-6 backdrop-blur-sm">
        <h2 className="text-2xl font-bold mb-4">Text to Video</h2>
        <textarea
          className="w-full h-32 rounded-lg bg-slate-800/70 ring-1 ring-white/10 p-4 outline-none focus:ring-2 focus:ring-sky-500"
          placeholder="A footballer scoring a goal in slow motion with crowd cheering."
          value={prompt}
          onChange={(e) => setPrompt(e.target.value)}
        />
        <div className="mt-4 flex flex-col sm:flex-row gap-4 items-center">
          <select
            className="w-full sm:w-auto bg-slate-800/70 ring-1 ring-white/10 rounded-lg px-4 py-2"
            value={duration}
            onChange={(e) => setDuration(Number(e.target.value))}
          >
            {DURATIONS.map((d) => (
              <option key={d.value} value={d.value}>{d.label}</option>
            ))}
          </select>
          <button
            onClick={handleGenerate}
            disabled={loading}
            className="inline-flex items-center justify-center gap-2 rounded-xl bg-gradient-to-r from-indigo-500 via-sky-500 to-purple-500 px-6 py-3 text-base font-semibold text-white shadow-lg shadow-indigo-900/30 disabled:opacity-60"
          >
            {loading ? <Loader2 className="w-5 h-5 animate-spin" /> : null}
            {loading ? 'Generating...' : 'Generate Video'}
          </button>
        </div>
        {loading && (
          <div className="mt-6 h-2 w-full bg-slate-800 rounded-full overflow-hidden">
            <div className="h-full w-1/3 animate-[progress_1.2s_ease_infinite] bg-gradient-to-r from-indigo-500 via-sky-500 to-purple-500" />
          </div>
        )}
        {error && <p className="mt-4 text-red-400 text-sm">{error}</p>}
      </div>

      {videoUrl && (
        <div className="mt-8 rounded-2xl bg-slate-900/60 ring-1 ring-white/10 p-6">
          <div className="relative">
            <video id="preview-video" className="w-full rounded-lg" src={videoUrl} onPlay={() => setPlaying(true)} onPause={() => setPlaying(false)} controls />
            <span className="absolute bottom-2 right-2 text-[10px] text-white/80 bg-black/50 px-2 py-1 rounded">Generated by VisionFlow AI</span>
          </div>
          <div className="mt-4 flex flex-wrap gap-3">
            <button onClick={() => document.getElementById('preview-video')?.play()} className="inline-flex items-center gap-2 px-4 py-2 rounded-lg bg-slate-800/80">
              <Play className="w-4 h-4" /> Play
            </button>
            <button onClick={() => document.getElementById('preview-video')?.pause()} className="inline-flex items-center gap-2 px-4 py-2 rounded-lg bg-slate-800/80">
              <Pause className="w-4 h-4" /> Pause
            </button>
            <a href={videoUrl} download className="inline-flex items-center gap-2 px-4 py-2 rounded-lg bg-slate-800/80">
              <Download className="w-4 h-4" /> Download
            </a>
            <button onClick={() => navigator.share ? navigator.share({ title: 'VisionFlow AI Video', url: videoUrl }) : navigator.clipboard.writeText(videoUrl)} className="inline-flex items-center gap-2 px-4 py-2 rounded-lg bg-slate-800/80">
              <Share2 className="w-4 h-4" /> Share
            </button>
          </div>
        </div>
      )}

      <style>{`
        @keyframes progress { 0%{transform:translateX(-100%)} 50%{transform:translateX(0%)} 100%{transform:translateX(100%)} }
      `}</style>
    </section>
  );
}
